# Generated by Django 4.1.7 on 2023-05-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchoice",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="form_builder.field",
            ),
        ),
    ]
