# Generated by Django 4.1.7 on 2023-06-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0002_alter_fieldchoice_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("password", "Password"),
                    ("number", "Number"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("radio", "radio"),
                    ("checkbox", "Checkbox"),
                    ("select", "Select"),
                ],
                max_length=50,
            ),
        ),
    ]
